version: "3.8"
services:
  api:
    build: .
    container_name: breakout_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  streamlit:
    build: .
    container_name: breakout_streamlit
    env_file:
      - .env
    ports:
      - "8501:8501"
    command: streamlit run app_streamlit.py --server.port 8501 --server.address 0.0.0.0
